"""empty message

Revision ID: 285a90ddaed1
Revises: 3408a3f461fe
Create Date: 2025-05-01 16:28:52.104032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285a90ddaed1'
down_revision = '3408a3f461fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_data')
    # ### end Alembic commands ###
